/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ftppackage;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPClient;
import org.jfree.ui.RefineryUtilities;
import twitter4j.Status;
import twitter4j.TwitterFactory;
import twitter4j.conf.ConfigurationBuilder;

/**
 *
 * @author comp
 */
public class FinalFrameForTwitter extends javax.swing.JFrame {

        int pCount = 0;
        int nCount = 0;
        int pNCount = 0;
        int nPCount = 0;
        int ppCount = 0;
        int nnCount = 0;
        
        ArrayList<String> alltweets = new ArrayList<String>();
    ArrayList<String> possdic = new ArrayList<String>();
    ArrayList<String> negdic = new ArrayList<String>();
    public FinalFrameForTwitter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tweets1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tweet2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tweets3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        tweets2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ltweet1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ltweet2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ltweet3 = new javax.swing.JTextArea();
        load1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        load3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 670));
        getContentPane().setLayout(null);

        tweets1.setColumns(20);
        tweets1.setRows(5);
        jScrollPane1.setViewportView(tweets1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 290, 140);

        tweet2.setColumns(20);
        tweet2.setRows(5);
        jScrollPane2.setViewportView(tweet2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 50, 290, 140);

        tweets3.setColumns(20);
        tweets3.setRows(5);
        jScrollPane3.setViewportView(tweets3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(700, 46, 280, 140);

        jButton1.setText("post");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 200, 120, 30);

        tweets2.setText("post");
        tweets2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweets2ActionPerformed(evt);
            }
        });
        getContentPane().add(tweets2);
        tweets2.setBounds(440, 200, 130, 33);

        jButton3.setText("post");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(800, 200, 130, 30);

        ltweet1.setColumns(20);
        ltweet1.setRows(5);
        jScrollPane4.setViewportView(ltweet1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(40, 260, 290, 178);

        ltweet2.setColumns(20);
        ltweet2.setRows(5);
        jScrollPane5.setViewportView(ltweet2);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(370, 260, 290, 178);

        ltweet3.setColumns(20);
        ltweet3.setRows(5);
        jScrollPane6.setViewportView(ltweet3);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(700, 260, 280, 178);

        load1.setText("load");
        load1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load1ActionPerformed(evt);
            }
        });
        getContentPane().add(load1);
        load1.setBounds(120, 470, 120, 32);

        jButton5.setText("load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(450, 470, 130, 32);

        load3.setText("load");
        load3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load3ActionPerformed(evt);
            }
        });
        getContentPane().add(load3);
        load3.setBounds(820, 470, 130, 32);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tweeter1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 20, 66, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tweeter2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 20, 66, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tweeter3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(810, 20, 66, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ftppackage/twitter2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 670));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 670));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 670));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
            
            ConfigurationBuilder cb = new ConfigurationBuilder();
          cb.setDebugEnabled(true)
                .setOAuthConsumerKey("8BByjeIznnxsEkaZmzk97DdHj")
                .setOAuthConsumerSecret("RhLfThMNUfiHNwc10I3FEn77xECNRjuaM0O2yBkdPAi3nsi0oE")
                .setOAuthAccessToken("986143851910979584-pQFmuxvymfZYUuS1cPqkLJ2QO83Iayg")
                .setOAuthAccessTokenSecret("eojPjR4gUy1t4rDI9nS1bGJRzusOhlJSBI5E4goPT86oi");
          
          
     TwitterFactory tf=new TwitterFactory(cb.build());  
     String EOL1 = "\r\n";
     twitter4j.Twitter tw=tf.getInstance();
     String myTweet=tweets1.getText();
     Status stat= tw.updateStatus(myTweet);
          
          System.out.println("Twitter updated");
          JOptionPane.showMessageDialog(null, "Twitter updated");
    }                                        
catch(Exception e)
        {
            System.out.println("dfd"+ e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void load1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load1ActionPerformed
       try{
           ltweet1.removeAll();
           ltweet1.setText("");
           ConfigurationBuilder cb = new ConfigurationBuilder();
            cb.setDebugEnabled(true)
                .setOAuthConsumerKey("8BByjeIznnxsEkaZmzk97DdHj")
                .setOAuthConsumerSecret("RhLfThMNUfiHNwc10I3FEn77xECNRjuaM0O2yBkdPAi3nsi0oE")
                .setOAuthAccessToken("986143851910979584-pQFmuxvymfZYUuS1cPqkLJ2QO83Iayg")
                .setOAuthAccessTokenSecret("eojPjR4gUy1t4rDI9nS1bGJRzusOhlJSBI5E4goPT86oi");


            TwitterFactory tf=new TwitterFactory(cb.build());  

            twitter4j.Twitter tw=tf.getInstance();
            List<Status> status=  tw.getHomeTimeline();
            String allTweets="";
            String EOL = "\r\n";
            for (Status status1 : status)
            {
                
              System.out.println(status1.getUser().getName() + ":" + status1.getText());
              System.out.println("location>>"+status1.getUser().getLocation());
               System.out.println("language>>"+status1.getUser().getLang());
               allTweets +=status1.getUser().getName() + ":" + status1.getText() + EOL;
               ltweet1.append(status1.getUser().getName() + ":" + status1.getText() + ":" + status1.getUser().getLocation() + ":" + status1.getUser().getLang() + EOL);
                
                
                System.out.println(status1);
            }

              FileOutputStream fos= new FileOutputStream("alltweets1.txt");
              fos.write(allTweets.getBytes());
              fos.close();
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_load1ActionPerformed

    private void tweets2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweets2ActionPerformed
        try{
          ConfigurationBuilder cb = new ConfigurationBuilder();
          cb.setDebugEnabled(true)
                .setOAuthConsumerKey("pARjgjmbP1fbSewvoaKemtmdf")
                .setOAuthConsumerSecret("HwFgxAygajc2JHT3ifIN0mKsCSupVjwRvPw2h0Q1n1GjuCIodk")
                .setOAuthAccessToken("986145918436208640-bYQkALwjwfP4O8R2FrX7E94UngpYkwR")
                .setOAuthAccessTokenSecret("uBRfDPXUmHGrmIS9tNhfE0gaPYz2rEAhqtoainaiId9o7");
          
          
         TwitterFactory tf=new TwitterFactory(cb.build());  
     String EOL1 = "\r\n";
     twitter4j.Twitter tw=tf.getInstance();
     String myTweet=tweet2.getText();
     Status stat= tw.updateStatus(myTweet);
          
          System.out.println("Twitter updated");
          JOptionPane.showMessageDialog(null, "Twitter updated");
                           
        }catch(Exception e1)
        {
            System.out.println(e1);
        }
    }//GEN-LAST:event_tweets2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try{
            ltweet2.removeAll();
            ltweet2.setText("");
        ConfigurationBuilder cb1 = new ConfigurationBuilder();
            cb1.setDebugEnabled(true)
                .setOAuthConsumerKey("pARjgjmbP1fbSewvoaKemtmdf")
                .setOAuthConsumerSecret("HwFgxAygajc2JHT3ifIN0mKsCSupVjwRvPw2h0Q1n1GjuCIodk")
                .setOAuthAccessToken("986145918436208640-bYQkALwjwfP4O8R2FrX7E94UngpYkwR")
                .setOAuthAccessTokenSecret("uBRfDPXUmHGrmIS9tNhfE0gaPYz2rEAhqtoainaiId9o7");


            TwitterFactory tf1=new TwitterFactory(cb1.build());  

            twitter4j.Twitter tw1=tf1.getInstance();
            List<Status> status1=  tw1.getHomeTimeline();
            String allTweets1="";
            String EOL1 = "\r\n";
            for (Status status11 : status1)
            {
              System.out.println(status11.getUser().getName() + ":" + status11.getText());
              System.out.println("location>>"+status11.getUser().getLocation());
               System.out.println("language>>"+status11.getUser().getLang());
               allTweets1 +=status11.getUser().getName() + ":" + status11.getText()  + EOL1;
               ltweet2.append(status11.getUser().getName() + ":" + status11.getText() + ":" + status11.getUser().getLocation() + ":" + status11.getUser().getLang() + EOL1);
            }
              FileOutputStream fos1= new FileOutputStream("alltweets2.txt");
              fos1.write(allTweets1.getBytes());
              fos1.close();
       
//              FileOutputStream fos11= new FileOutputStream("alltweets.txt");
//              fos1.write(allTweets1.getBytes());
//              fos1.close();
        
        
        }catch(Exception e)
              {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try{
         ConfigurationBuilder cb = new ConfigurationBuilder();
          cb.setDebugEnabled(true)
                .setOAuthConsumerKey("TNMbDwAe4nbkfucGgmelbNsy6")
                .setOAuthConsumerSecret("BeqYt3Rycdioi9t96AqY5iu07XCBY3ydNi9Qzpm5qeYJ72Mgox")
                .setOAuthAccessToken("986147732531359744-oLjKd0vK2dR2KrROCzBFfyHMSu34lm0")
                .setOAuthAccessTokenSecret("6yfeNlOdkNyTMXHmbfa8cNtG69zuvmVZ0kCYdp0Y3b47B");
          
          
         TwitterFactory tf=new TwitterFactory(cb.build());  
     String EOL1 = "\r\n";
     twitter4j.Twitter tw=tf.getInstance();
     String myTweet=tweets3.getText();
     Status stat= tw.updateStatus(myTweet);
          
          System.out.println("Twitter updated");
          JOptionPane.showMessageDialog(null, "Twitter updated");
                           
        }catch(Exception e1)
        {
            System.out.println(e1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void load3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load3ActionPerformed
        try{
            ltweet3.removeAll();
            ltweet3.setText("");
        ConfigurationBuilder cb1 = new ConfigurationBuilder();
            cb1.setDebugEnabled(true)
                  .setOAuthConsumerKey("TNMbDwAe4nbkfucGgmelbNsy6")
                .setOAuthConsumerSecret("BeqYt3Rycdioi9t96AqY5iu07XCBY3ydNi9Qzpm5qeYJ72Mgox")
                .setOAuthAccessToken("986147732531359744-oLjKd0vK2dR2KrROCzBFfyHMSu34lm0")
                .setOAuthAccessTokenSecret("6yfeNlOdkNyTMXHmbfa8cNtG69zuvmVZ0kCYdp0Y3b47B");
            TwitterFactory tf1=new TwitterFactory(cb1.build());  

            twitter4j.Twitter tw1=tf1.getInstance();
            List<Status> status1= new ArrayList<Status>();
            status1.clear();
            status1 = tw1.getHomeTimeline();
            String allTweets1="";
            String EOL1 = "\r\n";
            for (Status status11 : status1)
            {
              //System.out.println(status11.getUser().getName() + ":" + status11.getText());
             // System.out.println("location>>"+status11.getUser().getLocation());
              // System.out.println("language>>"+status11.getUser().getLang());
               allTweets1 +=status11.getUser().getName() + ":" + status11.getText()  + EOL1;
               ltweet3.append(status11.getUser().getName() + ":" + status11.getText() + ":" + status11.getUser().getLocation() + ":" + status11.getUser().getLang() + EOL1);
            }
              FileOutputStream fos1= new FileOutputStream("alltweets3.txt");
              fos1.write(allTweets1.getBytes());
              fos1.close();
        
FileInputStream fis11 = new FileInputStream("alltweets1.txt");
byte bb11[] = new byte[fis11.available()];
fis11.read(bb11);
fis11.close();
String all = new String(bb11);

FileInputStream fis12 = new FileInputStream("alltweets2.txt");
byte bb12[] = new byte[fis12.available()];
fis12.read(bb12);
fis12.close();
String all1 = new String(bb12);

FileInputStream fis13 = new FileInputStream("alltweets3.txt");
byte bb13[] = new byte[fis13.available()];
fis13.read(bb13);
fis13.close();
String all2 = new String(bb13);

FileOutputStream fos11 = new FileOutputStream("wholetweets.txt");
 fos11.write(bb11);
 fos11.write(bb12);
 fos11.write(bb13);
 //fos11.close();
 
 
 
 //  ftp merging code starts...
//        String server = "files.000webhost.com";
//        int port = 21;
//        String user = "sentimentalanalysis";
//        String pass = "testing1234";
//        FTPClient ftpClient = new FTPClient();
//        
//        ftpClient.connect(server, port);
//        ftpClient.login(user, pass);
//        ftpClient.enterLocalPassiveMode();
//        ftpClient.setFileType(FTP.BINARY_FILE_TYPE);
//        File firstLocalFile = new File("alltweetsfinalftp.txt");
//        String firstRemoteFile = "fresh1.txt";  
//       OutputStream outputStream = new FileOutputStream(firstLocalFile);
//       boolean done = ftpClient.retrieveFile(firstRemoteFile, outputStream);
//       outputStream.close();
//       if (done) {
//        //System.out.println("The first file is Downloaded successfully.");
//        //JOptionPane.showMessageDialog(null, "file is Downloaded successfully");
//        //Runtime.getRuntime().exec("notepad alltweetsfinal.txt");
//            }
//       else{
//         JOptionPane.showMessageDialog(null,"problem in loading the FTP tweets dat");
//       }
       FileInputStream fisFTP = new FileInputStream("alltweetsfinalftp.txt");
       byte bbFTP[] = new byte[fisFTP.available()];
       fisFTP.read(bbFTP);
       fisFTP.close();
       String ftpTotTweets = new String(bbFTP);
       
       ArrayList<String> allFTPRelavantTweets = new ArrayList<String>();
       allFTPRelavantTweets.clear();
       
       StringTokenizer stFTP = new StringTokenizer(ftpTotTweets,"\r\n");
       while(stFTP.hasMoreTokens()){
           String tFTPTweet = stFTP.nextToken();
          // if(tFTPTweet.startsWith("sandeep")){
               allFTPRelavantTweets.add(tFTPTweet);
          // }
       }
       
       String totFTPString = new String();
       for(int l=0;l<allFTPRelavantTweets.size();l++){
           totFTPString += allFTPRelavantTweets.get(l)+"\r\n";
       }
       
       fos11.write(totFTPString.getBytes());
       fos11.close();
 //  ftp merging code ends..


        }catch(Exception e){
            System.out.println(e);
        }    
    }//GEN-LAST:event_load3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalFrameForTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalFrameForTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalFrameForTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalFrameForTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
         FinalFrameForTwitter t= new FinalFrameForTwitter();
         t.setVisible(true);
         t.setSize(1000,670);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton load1;
    private javax.swing.JButton load3;
    private javax.swing.JTextArea ltweet1;
    private javax.swing.JTextArea ltweet2;
    private javax.swing.JTextArea ltweet3;
    private javax.swing.JTextArea tweet2;
    private javax.swing.JTextArea tweets1;
    private javax.swing.JButton tweets2;
    private javax.swing.JTextArea tweets3;
    // End of variables declaration//GEN-END:variables
}
